### ISSUE TITLE
Issues with downloading flow

### ISSUE THREAD

**Issue by willprice** [epic-kitchens/starter-kit-action-recognition#1]
*Issue received via email follow after break*

---

I am trying to download the videos of epic kitchen and create the gulp 
files. Due to limitations in memory space i modified the snakemake in 
order to treat separately train, test seen and unseen, flow and rgb. At 
the moment i am trying to download only the rgb training set. 

For some reason i am not able to complete the download using Snakemake. 
Seems that a file is missing. 
I get the following print out: 

```
HTTP request sent, awaiting response... 200 OK 
Length: 98283520 (94M) [application/x-tar] 
Saving to: ‘/tmp/data/raw/flow/P29/P29_04.tar’ 

/tmp/data/raw/flow/P29/P29_04.tar 0%[ 
] 0 --.-KB/s in 0s 

Cannot write to ‘/tmp/data/raw/flow/P29/P29_04.tar’ (Success). 
Waiting at most 60 seconds for missing files. 
```

Any clue about the causes?

**Comment by willprice** [comment]
Your first step would be to check whether you have any partially downloaded files in that directory (`/tmp/data/raw/flow/P29/`), does it exist? 

It looks like you have permission errors writing to that directory, perhaps change `tmp_dir` in `config.yml` to `data` (so that files are extracted to the `./data` dir in your current working directory instead of to `/tmp`), I presume you changed `tmp_dir` to `/tmp`? 

Providing `/tmp/data/raw/flow/P29/` exists, can you provide the output of the following commands:
-  `ls -lah `/tmp/data/raw/flow/P29/`
- `echo $USER`

**Comment by Schiboni** [comment]
Dear Will, thanks for your quick answer. I found the mistake, that was actually silly. I just ran out of memory space. I let to you the decision to erase this issue or just close it.

**Comment by willprice** [comment]
Hi @Schiboni, no worries, easily done.
I'll leave the issue as this can happen when you have insufficient space in the `tmp_dir` directory.
