### ISSUE TITLE
Missing data in Snakemake download

### ISSUE THREAD

**Issue by aoikaneko** [epic-kitchens/starter-kit-action-recognition#10]
Hi, I've downloaded the dataset in two ways: using Snakemake vs. download script (https://github.com/epic-kitchens/download-scripts/blob/master/download_frames_rgb_flow.sh).

The download script downloaded all the data. However, in Snakemake, two training data seems to be missing: `P06_04` and `P06_06`. (`train_video_ids.csv` doesn't have the two ids)

Thank you for the great dataset!

**Comment by willprice** [comment]
Hi @aoikaneko,
You're right that those files don't exist, it's because those videos were too short to be worthy of narration. If you have all the videos listed in `train_video_ids.csv` then you have the full training set.
I hope that helps.
