### ISSUE TITLE
Snakemake gulp download Error

### ISSUE THREAD

**Issue by arnavc1712** [epic-kitchens/starter-kit-action-recognition#11]
Hi,
I am getting the following error when I execute ```snakemake -p gulp_all```

> Command ' set -euo pipefail;  
        mkdir -p data/interim/rgb_train_segments/P14/P14_09
        python -m epic_kitchens.preprocessing.split_segments           $(basename data/raw/rgb/P14/P14_09)           data/raw/rgb/P14/P14_09           data/interim/rgb_train_segments/P14/P14_09           data/processed/train_labels.pkl           rgb           --fps 60           --frame-format 'frame_%010d.jpg'           --of-stride 2           --of-dilation 3 ' returned non-zero exit status 1.
  File "/epickitchens/epic/Snakefile", line 156, in __rule_segment_frames_for_video
  File "/home/ec2-user/miniconda3/envs/epic/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job segment_frames_for_video since they might be corrupted:
data/interim/rgb_train_segments/P14/P14_09
Shutting down, this might take some time.

**Comment by willprice** [comment]
Are there any python stack traces you can provide? Can you try running 
```bash
$ mkdir -p data/interim/rgb_train_segments/P14/P14_09
$ python -m epic_kitchens.preprocessing.split_segments \
    $(basename data/raw/rgb/P14/P14_09) data/raw/rgb/P14/P14_09 \
    data/interim/rgb_train_segments/P14/P14_09 \
    data/processed/train_labels.pkl rgb \
    --fps 60 --frame-format 'frame_%010d.jpg' --of-stride 2 --of-dilation 3 
```
from the root of the directory (you'll need to make sure `data/raw/rgb/P14/P14_09` exists and has all the frames extracted from the corresponding tar file.

**Comment by arnavc1712** [comment]
Hi WIll,
It seems to be working now. It was apparently some OpenCV error. Thanks for your help.
