### ISSUE TITLE
How can the gulped data be used for Action Anticipation

### ISSUE THREAD

**Issue by arnavc1712** [epic-kitchens/starter-kit-action-recognition#12]
I ran 'snakemake -p gulp_all', and got the gulp directories. I am wondering how do I set the anticipation time (Ta) = 1 second? 
For one segment: **('start_frame', 262), ('stop_frame', 370),**
And then the next segment: **('start_frame', 418), ('stop_frame', 569)**

In such a case how do we set Ta=1 second, for the anticipation time? Since for many segments, the difference in time between 2 segments is more than 1 second?

**Comment by dimadamen** [comment]
Thanks for your question. This repo is primarily designed to help you with the action-recognition challenge. For questions related to the action anticipation or object detection challenges, please email the dataset's general info: uob-epic-kitchens2018@bristol.ac.uk
This will allow us to direct the question to the relevant researcher.
