### ISSUE TITLE
Gulp For KITCHENS-100?

### ISSUE THREAD

**Issue by RaivoKoot** [epic-kitchens/starter-kit-action-recognition#15]
In the README it says that running   
`snakemake -p gulp_all`   
will download and gulp KITCHENS-55. Is this also somehow possible for the new, entire KITCHENS-100, or is this repository only for KITCHENS-55?

Thanks a lot!

**Comment by willprice** [comment]
Hey @RaivoKoot,
Check out https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#prep-data, I scrapped the snakemake pipeline for EPIC-Kitchens-100 data prep, we now skip the step of segmenting frames into action folders and then gulping from that. Instead we just read directly from the raw directory full of frames for each video using the narrations. It's a more flexible/robust/simpler approach :)

**Comment by RaivoKoot** [comment]
Oh thats amazing thank you! Its working and agree, seems simpler :)

**Comment by willprice** [comment]
Great, glad you got it working :) thanks for letting me know.
