### ISSUE TITLE
What model to use to replicate results of the Epic Kitchen paper?

### ISSUE THREAD

**Issue by Schiboni** [epic-kitchens/starter-kit-action-recognition#2]
Hi,
i want to reproduce your experiment of action recognition from the Epic Kitchen paper. I am struggling to understand what model you used among those provided by torchvision, i.e.,
inceptionresnetv2.lua
inceptionv3.lua
inceptionv4.lua

Thanks and best regards,
Giovanni

**Comment by willprice** [comment]
We used https://github.com/yjxiong/tsn-pytorch modified to have two output layers, one for verbs and one for nouns. We use pytorch, not torch.

For 2SCNN results we use the same code base setting the number of segments to 1.

**Comment by Schiboni** [comment]
"We used https://github.com/yjxiong/tsn-pytorch modified to have two output layers, one for verbs and one for nouns. We use pytorch, not torch." 
Yes that is clear, i have modified that code to have the two output layers, one for verbs and one for nouns, as you suggested.

My problem is to understand how to load the pretrained model to put in the variable "base_model" in TSN(nn.Module).

**Comment by willprice** [comment]
We used `BNInception` with ImageNet weights.

**Comment by Schiboni** [comment]
Many thanks.
