### ISSUE TITLE
Clarification of flow dataset

### ISSUE THREAD

**Issue by kylemin** [epic-kitchens/starter-kit-action-recognition#4]
Let's say we have an image sequence (I1, I2, I3, ...).
How did you generate u and v? Did you use the following equation?
u1 = flow_x(I1, I2)
v1 = flow_y(I2, I3)

**Comment by dimadamen** [comment]
Please read the paper for these details, we do extract flow with a 3-frame gap to avoid flicker.

**Comment by kylemin** [comment]
Got it, thanks.

**Comment by kylemin** [comment]
One more question:
Exactly how did you bound/normalize each flow data?
e.x.
bound=20
flow[flow>bound] = bound
flow[flow<-bound] = -bound
flow += bound
flow = (255./(2bound))
