### ISSUE TITLE
normalization of flow image

### ISSUE THREAD

**Issue by kylemin** [epic-kitchens/starter-kit-action-recognition#5]
Exactly how did you bound/normalize each flow data?
e.x.
bound=20
flow[flow>bound] = bound
flow[flow<-bound] = -bound
flow += bound
flow = (255./(2bound))

**Comment by willprice** [comment]
Bound was 25, you can find the code we used here : https://github.com/dl-container-registry/furnari-flow?files=1, it is a fork of Chris Feichtenhofer's code.

**Comment by kylemin** [comment]
Thanks.
