### ISSUE TITLE
How to draw the bounding boxes of object detection?

### ISSUE THREAD

**Issue by kylemin** [epic-kitchens/starter-kit-action-recognition#6]
I am following the second notebook: :Reading frames with GulpIO"
How can I draw the bounding boxes, which are annotated at 2fps?

**Comment by dimadamen** [comment]
Thanks for your question. This repo is primarily designed to help you with the action-recognition challenge. For questions related to the action anticipation or object detection challenges, please email the dataset's general info: uob-epic-kitchens2018@bristol.ac.uk
This will allow us to direct the question to the relevant researcher.
