### ISSUE TITLE
Process data after manually downloaded

### ISSUE THREAD

**Issue by amjltc295** [epic-kitchens/starter-kit-action-recognition#9]
I already download the data with the scripts in https://github.com/epic-kitchens/download-scripts
However, I could not find how to extra these .tars and make them gulp dataset that could be read by the epic-kitchens lib.

I've tried to read the Snakemake file, yet the download speed is a bit slow. 
How could I use snakemake to create the same results as `snakemake -p gulp_all` with downloaded .tars? The downloaded files are int `/tmp/epic_kitchen` and I've changed the tmp dir in `config.yaml`

**Comment by willprice** [comment]
Hi there,
If you've downloaded the RGB and flow tars, you should be able to put them in the location snakemake is expecting them to be present (`data/raw/$modality/$participant/$participant_video.tar`, e.g. `data/raw/rgb/P01/P01_01.tar`), you might in addition have to 'touch' them so snakemake registers their existance:
```
# For both RGB and flow frames
$ snakemake -t download_all_frames

# Or for just RGB
$ snakemake -t download_all_rgb_frames

# Or for just flow
$ snakemake -t download_all_flow_frames
```
(see https://bitbucket.org/snakemake/snakemake/src/e049f5e49635ff9c56544a7b1efb5e1a193e1530/snakemake/__init__.py?at=master&fileviewer=file-view-default#__init__.py-776) or `snakemake --help`

Once you've done that you should be able to go ahead and run `snakemake -p gulp_all`
